name: Scrape Premier League Table

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v5.2.0
      with:
        go-version: '1.21'
        
    - name: Initialize Go module
      run: |
        go mod init premier-league-scraper
            
    - name: Run scraper
      run: |
        go run test.go
        
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add premier_league_table.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Premier League table data $(date)" && git push)
